const $=s=>document.querySelector(s); const storeKey='koreanStudyLearnersV1';
const countries={KR:{name:'대한민국',birth:'출생년도',family:'성',given:'이름'},CA:{name:'Canada',birth:'출생년도 · Birth year',family:'성 · Family name',given:'이름 · Given name'},US:{name:'United States',birth:'출생년도 · Birth year',family:'성 · Family name',given:'이름 · Given name'},JP:{name:'日本',birth:'출생년도 · 生まれた年',family:'성 · 姓',given:'이름 · 名'},CN:{name:'中国',birth:'출생년도 · 出生年份',family:'성 · 姓',given:'이름 · 名'}};
let selectedCountry=null, learner=null, idx=0, answers=[], recognition=null, finalTranscript='';
const year=new Date().getFullYear(); for(let y=year-3;y>=1940;y--){const o=document.createElement('option');o.value=y;o.textContent=y;$('#birthYear').append(o)}
Object.entries(countries).forEach(([code,c])=>{let b=document.createElement('button');b.type='button';b.className='country';b.textContent=c.name;b.onclick=()=>selectCountry(code,b);$('#countries').append(b)});
function selectCountry(code,b){selectedCountry=code;document.querySelectorAll('.country').forEach(x=>x.classList.remove('active'));b.classList.add('active');let c=countries[code];$('#birthLabel').textContent=c.birth;$('#familyLabel').textContent=c.family;$('#givenLabel').textContent=c.given;$('#localized').hidden=false}
function learners(){return JSON.parse(localStorage.getItem(storeKey)||'[]')} function saveLearners(a){localStorage.setItem(storeKey,JSON.stringify(a))}
$('#tabNew').onclick=()=>{$('#newForm').hidden=false;$('#backForm').hidden=true;$('#tabNew').classList.add('active');$('#tabBack').classList.remove('active')};$('#tabBack').onclick=()=>{$('#newForm').hidden=true;$('#backForm').hidden=false;$('#tabBack').classList.add('active');$('#tabNew').classList.remove('active')};
$('#newForm').onsubmit=e=>{e.preventDefault();if(!selectedCountry)return $('#gateMsg').textContent='거주국가를 먼저 선택해 주세요.';let l={id:crypto.randomUUID(),country:selectedCountry,birthYear:+$('#birthYear').value,family:$('#familyName').value.trim(),given:$('#givenName').value.trim(),createdAt:new Date().toISOString()};let a=learners();a.push(l);saveLearners(a);start(l)};
$('#backForm').onsubmit=e=>{e.preventDefault();let f=$('#backFamily').value.trim(),g=$('#backGiven').value.trim(),m=learners().filter(x=>x.family===f&&x.given===g);if(m.length===1)start(m[0]);else if(m.length>1)$('#gateMsg').textContent='같은 이름이 여러 명 있어요. 처음 등록 화면에서 다시 등록하거나 선생님에게 확인해 주세요.';else $('#gateMsg').textContent='등록 정보를 찾지 못했어요. 처음이라면 “처음이에요”에서 등록해 주세요.'};
function ageBand(y){let a=year-y;if(a<=8)return'child';if(a<=12)return'upper';if(a<=17)return'teen';return'adult'}
const bank={child:[
{d:'듣기',t:'선생님 말을 듣고 고르기',p:'선생님이 “비가 오니까 우산을 가져가세요.”라고 말했어요. 왜 우산을 가져가야 할까요?',type:'choice',c:['날씨가 더워서','비가 와서','학교에 가서'],a:1},
{d:'읽기',t:'생활 한국어 읽기',p:'“경기 시작 30분 전 입장 / 외부 음식 반입 금지”\n경기장에 밖에서 산 음식을 가져가도 될까요?',type:'choice',c:['네','아니요'],a:1},
{d:'말하기',t:'내 경험 말하기',p:'최근에 재미있었던 일을 처음부터 끝까지 한국어로 이야기해 보세요.',type:'speech'},
{d:'쓰기',t:'짧게 쓰기',p:'좋아하는 것을 소개하고, 왜 좋아하는지 3~5문장으로 써 보세요.',type:'write'}],upper:[
{d:'듣기',t:'듣고 이유 파악하기',p:'선생님이 읽어 주세요: “민수는 버스를 놓쳤지만 택시를 타지 않고 다음 버스를 기다렸습니다. 약속 시간까지 여유가 있었고 돈도 아끼고 싶었기 때문입니다.”\n민수가 택시를 타지 않은 이유를 두 가지 말해 보세요.',type:'speech'},
{d:'읽기',t:'읽고 추론하기',p:'수아는 한국어로 말하는 것은 익숙했지만 메시지를 쓸 때는 영어 단어가 먼저 떠올랐습니다. 그래서 매일 가족에게 짧은 한국어 메시지를 보내기 시작했습니다. 몇 달 뒤에는 자신의 생각을 전보다 자연스럽게 적을 수 있었습니다.\n수아의 한국어 쓰기가 좋아진 가장 중요한 이유는 무엇이라고 생각하나요?',type:'write'},
{d:'말하기',t:'이유와 근거 말하기',p:'한국 또래 친구를 처음 만난다면 무엇을 같이 하고 싶나요? 이유도 함께 말해 보세요.',type:'speech'},
{d:'쓰기',t:'생각 연결하기',p:'한국어를 계속 배우면 나에게 어떤 점이 좋을까요? 구체적인 상황을 넣어 5~7문장으로 써 보세요.',type:'write'}],teen:[
{d:'읽기',t:'핵심과 관점 파악',p:'두 언어를 사용하는 사람은 상황에 따라 더 편한 언어를 선택합니다. 편한 언어로 바꾸는 것 자체가 문제는 아니지만, 한 언어를 사용할 기회가 계속 줄면 그 언어로 복잡한 생각을 표현하는 능력도 약해질 수 있습니다.\n이 글의 핵심 주장을 자기 말로 정리하세요.',type:'write'},
{d:'말하기',t:'의견 설명',p:'한국어를 유지하기 위해 일상에서 가장 효과적인 방법은 무엇이라고 생각하나요? 근거와 예를 들어 말해 보세요.',type:'speech'},
{d:'듣기',t:'정보 재구성',p:'선생님이 최근 있었던 일을 4~5문장으로 말해 주세요. 들은 뒤 핵심 내용을 순서대로 다시 설명해 보세요.',type:'speech'},
{d:'쓰기',t:'상황 글쓰기',p:'한국에 있는 친구에게 캐나다/미국/일본/중국 등 내가 사는 곳의 학교생활을 소개하는 메시지를 7문장 안팎으로 써 보세요.',type:'write'}],adult:[
{d:'읽기',t:'생활·업무 한국어',p:'“회의 자료는 오늘 오후 3시까지 공유해 주세요. 검토 의견은 내일 오전 회의 전에 문서에 남겨 주시면 됩니다.”\n해야 할 일을 시간 순서대로 정리하세요.',type:'write'},
{d:'말하기',t:'경험과 의견',p:'한국어를 사용하면서 가장 어려웠던 상황 하나를 설명하고, 어떻게 해결했는지 말해 보세요.',type:'speech'},
{d:'듣기',t:'요지 듣기',p:'선생님이 30초 정도의 일상 또는 업무 상황을 말해 주세요. 핵심 내용과 필요한 행동을 다시 설명해 보세요.',type:'speech'},
{d:'쓰기',t:'실용 글쓰기',p:'약속 시간을 변경해야 하는 상황입니다. 상대에게 이유, 새 시간, 미안한 마음을 포함한 메시지를 써 보세요.',type:'write'}]};
function start(l){learner=l;idx=0;answers=[];$('#gate').hidden=true;$('#done').hidden=true;$('#assessment').hidden=false;$('#learnerName').textContent=l.given;$('#levelNote').textContent=`출생년도 ${l.birthYear}년을 기준으로 연령대에 맞는 문항이 제시됩니다.`;render()}
function tasks(){return bank[ageBand(learner.birthYear)]} function render(){let q=tasks()[idx];$('#bar').style.width=`${idx/tasks().length*100}%`;$('#domain').textContent=q.d;$('#counter').textContent=`${idx+1} / ${tasks().length}`;$('#taskTitle').textContent=q.t;$('#taskText').textContent=q.p;$('#choiceBox').innerHTML='';$('#writeBox').hidden=q.type!=='write';$('#writeBox').value='';$('#speechBox').hidden=q.type!=='speech';$('#feedback').hidden=true;$('#transcript').hidden=true;finalTranscript='';if(q.type==='choice')q.c.forEach((x,i)=>{let b=document.createElement('button');b.type='button';b.className='choice';b.textContent=x;b.onclick=()=>{document.querySelectorAll('.choice').forEach(z=>z.classList.remove('selected'));b.classList.add('selected');b.dataset.pick=i};$('#choiceBox').append(b)})}
$('#nextBtn').onclick=()=>{let q=tasks()[idx],value='';if(q.type==='choice'){let s=$('.choice.selected');if(!s)return alert('하나를 골라 주세요.');value=+s.dataset.pick}else if(q.type==='write'){value=$('#writeBox').value.trim();if(!value)return alert('짧게라도 답을 써 주세요.')}else{value=finalTranscript;if(!value)return alert('말하기를 먼저 해 주세요.')}answers.push({domain:q.d,type:q.type,value,correct:q.a===undefined?null:value===q.a});idx++;if(idx>=tasks().length)finish();else render()};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR();recognition.lang='ko-KR';recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let all='';for(let i=e.resultIndex;i<e.results.length;i++)all+=e.results[i][0].transcript;finalTranscript=(finalTranscript+' '+all).trim();$('#transcript').textContent='인식된 말: '+finalTranscript;$('#transcript').hidden=false};recognition.onend=()=>{$('#speakBtn').disabled=false;$('#stopBtn').disabled=true;$('#speechStatus').textContent='녹음/인식이 끝났어요. 인식된 문장을 확인해 주세요.'}}
$('#speakBtn').onclick=()=>{if(!recognition){$('#speechStatus').textContent='이 브라우저는 실시간 한국어 음성인식을 지원하지 않아요. Chrome/Edge 최신 버전을 사용해 주세요.';return}finalTranscript='';recognition.start();$('#speakBtn').disabled=true;$('#stopBtn').disabled=false;$('#speechStatus').textContent='듣고 있어요… 자연스럽게 말해 주세요.'};$('#stopBtn').onclick=()=>recognition&&recognition.stop();
function domainScore(d){let xs=answers.filter(x=>x.domain===d);if(!xs.length)return null;let pts=xs.map(x=>x.type==='choice'?(x.correct?100:30):x.value.length>80?90:x.value.length>40?78:x.value.length>15?65:45);return Math.round(pts.reduce((a,b)=>a+b,0)/pts.length)}
function finish(){$('#assessment').hidden=true;$('#done').hidden=false;let ds=['듣기','말하기','읽기','쓰기'];$('#scoreCards').innerHTML=ds.map(d=>{let s=domainScore(d);return `<div class="score"><span>${d}</span><b>${s??'—'}</b><small>${s==null?'이번 진단 문항 없음':s>=85?'안정적':s>=70?'발전 중':'추가 확인'}</small></div>`}).join('');let spoken=answers.filter(x=>x.type==='speech').map(x=>x.value).join(' '),written=answers.filter(x=>x.type==='write').map(x=>x.value).join(' ');$('#summary').innerHTML=`<b>교사용 빠른 관찰 메모</b><br>말하기 인식 분량: ${spoken.length}자 · 쓰기 분량: ${written.length}자<br>※ 현재 점수는 객관식 정답과 응답 분량을 이용한 <b>1차 보조지표</b>입니다. 발음 정확도·문법·자연스러움은 교사가 실제 발화를 함께 확인해 최종 Assessment Report에 반영하세요.`;localStorage.setItem('koreanStudyLastResult',JSON.stringify({learner,answers,at:new Date().toISOString()}))}
$('#printBtn').onclick=()=>window.print();$('#restartBtn').onclick=()=>location.reload();$('#logout').onclick=()=>location.reload();